public class MathTester {
    public static void main(String[] args) {
        System.out.println("ABSOLUTE VALUE CHECKS");
        System.out.println("abs(   5) is "+Math.abs(   5)+", your answer is "+Tann_Math.abs(   5));
        System.out.println("abs(  -3) is "+Math.abs(  -3)+", your answer is "+Tann_Math.abs(  -3));
        System.out.println("abs( 2.0) is "+Math.abs( 2.0)+", your answer is "+Tann_Math.abs( 2.0));
        System.out.println("abs(-7.0) is "+Math.abs(-7.0)+", your answer is "+Tann_Math.abs(-7.0));
        System.out.println();
        System.out.println("CEIL CHECKS");
        System.out.println("ceil(3.0) is "+Math.ceil(3.0)+", your answer is "+Tann_Math.ceil(3.0));
        System.out.println("ceil(3.2) is "+Math.ceil(3.2)+", your answer is "+Tann_Math.ceil(3.2));
        System.out.println("ceil(3.5) is "+Math.ceil(3.5)+", your answer is "+Tann_Math.ceil(3.5));
        System.out.println("ceil(3.7) is "+Math.ceil(3.7)+", your answer is "+Tann_Math.ceil(3.7));
        System.out.println("ceil(4.0) is "+Math.ceil(4.0)+", your answer is "+Tann_Math.ceil(4.0));
        System.out.println();
        System.out.println("FLOOR CHECKS");
        System.out.println("floor(3.0) is "+Math.floor(3.0)+", your answer is "+Tann_Math.floor(3.0));
        System.out.println("floor(3.2) is "+Math.floor(3.2)+", your answer is "+Tann_Math.floor(3.2));
        System.out.println("floor(3.5) is "+Math.floor(3.5)+", your answer is "+Tann_Math.floor(3.5));
        System.out.println("floor(3.7) is "+Math.floor(3.7)+", your answer is "+Tann_Math.floor(3.7));
        System.out.println("floor(4.0) is "+Math.floor(4.0)+", your answer is "+Tann_Math.floor(4.0));
        System.out.println();
        System.out.println("ROUND CHECKS");
        System.out.println("round(3.0) is "+Math.round(3.0)+", your answer is "+Tann_Math.round(3.0));
        System.out.println("round(3.2) is "+Math.round(3.2)+", your answer is "+Tann_Math.round(3.2));
        System.out.println("round(3.5) is "+Math.round(3.5)+", your answer is "+Tann_Math.round(3.5));
        System.out.println("round(3.7) is "+Math.round(3.7)+", your answer is "+Tann_Math.round(3.7));
        System.out.println("round(4.0) is "+Math.round(4.0)+", your answer is "+Tann_Math.round(4.0));
        System.out.println();
        System.out.println("MAX AND MIN CHECKS");
        System.out.println("max(3.0, -2.0) is "+Math.max(3.0, -2.0)+", your answer is "+Tann_Math.max(3.0, -2.0));
        System.out.println("max(-0.5, 9.0) is "+Math.max(-0.5, 9.0)+", your answer is "+Tann_Math.max(-0.5, 9.0));
        System.out.println("min(2.1, -2.3) is "+Math.min(-2.3, 2.1)+", your answer is "+Tann_Math.min(-2.3, 2.1));
        System.out.println("min(-5.2, 3.3) is "+Math.min(-5.2, 3.3)+", your answer is "+Tann_Math.min(-5.2, 3.3));
        System.out.println();
        System.out.println("RANDOM CHECKS");
        System.out.println("random() check, your answer is "+Tann_Math.random());
        System.out.println("random() check, your answer is "+Tann_Math.random());
        System.out.println("random() check, your answer is "+Tann_Math.random());
        System.out.println("random() check, your answer is "+Tann_Math.random());
        System.out.println();
        System.out.println("POWER CHECKS");
        System.out.printf("pow(3,4) is \t %.5f, your answer is %.5f%n",Math.pow(3,4),Tann_Math.pow(3,4));
        System.out.printf("pow(2,0.5) is \t %.6f, your answer is %.6f%n",Math.pow(2,0.5),Tann_Math.pow(2,0.5));
        System.out.printf("pow(3.76,2) is \t %.5f, your answer is %.5f%n",Math.pow(3.76,2),Tann_Math.pow(3.76,2));
        System.out.printf("pow(2.2,1.12) is %.6f, your answer is %.6f%n",Math.pow(2.2,1.12),Tann_Math.pow(2.2,1.12));
        System.out.println();
        System.out.println("SQUARE ROOT CHECKS");
        System.out.printf("nrt(2,2) is %.5f, your answer is %.5f%n",Math.sqrt(2),Tann_Math.sqrt(2));
        System.out.printf("nrt(4,2) is %.5f, your answer is %.5f%n",Math.sqrt(4),Tann_Math.sqrt(4));
        System.out.printf("nrt(7,2) is %.5f, your answer is %.5f%n",Math.sqrt(7),Tann_Math.sqrt(7));
        System.out.printf("nrt(9,2) is %.5f, your answer is %.5f%n",Math.sqrt(9),Tann_Math.sqrt(9));
        System.out.println();
        System.out.println("LOGARITHM CHECKS");
        System.out.printf("log(3)  is %.5f, your answer is %.5f%n",Math.log10(3),Tann_Math.log(3));
        System.out.printf("log(6)  is %.5f, your answer is %.5f%n",Math.log10(6),Tann_Math.log(6));
        System.out.printf("log(10) is %.5f, your answer is %.5f%n",Math.log10(10),Tann_Math.log(10));
        System.out.printf("log(15) is %.5f, your answer is %.5f%n",Math.log10(15),Tann_Math.log(15));
        System.out.println();
        System.out.println("NATURAL LOG CHECKS");
        System.out.printf("ln(3)   is %.5f, your answer is %.5f%n",Math.log(3),Tann_Math.ln(3));
        System.out.printf("ln(6)   is %.5f, your answer is %.5f%n",Math.log(6),Tann_Math.ln(6));
        System.out.printf("ln(10)  is %.5f, your answer is %.5f%n",Math.log(10),Tann_Math.ln(10));
        System.out.printf("ln(15)  is %.5f, your answer is %.5f%n",Math.log(15),Tann_Math.ln(15));
    }
}
